# https://www.appveyor.com/docs/appveyor-yml/

environment:
  matrix:
  # node.js
    - nodejs_version: "6.9"
    - nodejs_version: "5.12"
    - nodejs_version: "4.6"
    - nodejs_version: "0.12"
  # io.js
    - nodejs_version: "3"
    - nodejs_version: "2"
    - nodejs_version: "1"

platform:
  - x64
  - x86

shallow_clone: true

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true

# build cache to preserve files/folders between builds
cache:
  - node_modules

# scripts that run after cloning repository
install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - node --version
  - npm --version
  - SET PATH=%APPDATA%\npm;%PATH%
  - npm update -g npm
  - npm --version
  - node -e "console.log(process.arch);"
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - if "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - if "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  - npm install
  - npm test

build: off
test: off
deploy: off
